### ISSUE TITLE
Request timeouts happen a lot for Daily

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/code_fund_ads#853]
# Bug Report

## Describe the bug

The API requests by Daily are timing out pretty regularly.

## Expected behavior

The API requests should be quicker

## Steps To Reproduce

Ask Ido

**Comment by idoshamun** [comment]
I'm here for any question, feel free to tag me in the conversation or reach out directly on your slack

**Comment by andrewmcodes** [comment]
Thank you so much @idoshamun!

**Comment by hopsoft** [comment]
I've noticed that our slowest traces on this endpoint are using `api/v1/...` or `scripts/.../embed.js` @idoshamun can you confirm what URL you're using for integration?

**Comment by idoshamun** [comment]
I use this endpoint `https://codefund.io/api/v1/impression/`.
Feel free to check the code as well if you want to dive deeper:
https://github.com/dailynowco/daily-monetization/blob/master/codefund.go#L49

**Comment by hopsoft** [comment]
Will you try the following 2 things? It will require some minor changes on your end but may yield some performance gains.

1. Update to use our new funder URL. `https://app.codefund.io/properties/PROPERTY_ID/funder.js`
2. Update the request to use the following header. `Accept-Encoding: gzip`

**Comment by idoshamun** [comment]
I must use the API endpoint. 
The call is done on our servers, not the client.

**Comment by andrewmcodes** [comment]
@idoshamun We've got you covered. The endpoint that @hopsoft listed

> https://app.codefund.io/properties/PROPERTY_ID/funder.js

Is an API endpoint that you can request as JavaScript, JSON, or HTML 

Ex:

```
https://app.codefund.io/properties/PROPERTY_ID/funder.js
https://app.codefund.io/properties/PROPERTY_ID/funder.json
https://app.codefund.io/properties/PROPERTY_ID/funder.html
```

Let me know if that will work or if there is more we can do to help/explain.

The API endpoint you are currently hitting returns the same thing (literally) as the JSON endpoint, but it should be a bit faster due to less logic that needs to happen on our end.

**Comment by idoshamun** [comment]
@andrewmcodes thanks for the clarification.
The response looks a bit different than the current API, I have some missing fields such as `link`, `pixel` and `large_image_url`.
Currently, `funder.json` doesn't look like something I can utilize as it requires me to parse the `html` field.

**Comment by hopsoft** [comment]
Note that the data exists on the new API but it's formatted slightly different. 

- `impressionUrl` = `pixel`
- `images.find(i => i.format === 'large')` = `large_image_url`

We had hoped to deprecate and remove legacy API support in April 2019, but have continued to support it given the difficulty of coordinating the efforts of all the consumers still using it. SEE: https://github.com/gitcoinco/code_fund_ads/blob/master/app/views/advertisements/legacy_show.json.jbuilder#L1-L2

---

Here's a screenshot of the new JSON API response payload.

<img width="965" alt="tmux -2 a 2019-12-04 12-43-02" src="https://user-images.githubusercontent.com/32920/70175404-e1a65780-1693-11ea-9fc8-8e0b73f65d24.png">

**Comment by idoshamun** [comment]
I have just merged the migration to your new API into master (https://github.com/dailynowco/daily-monetization/pull/9).
I will let you know if the situation got any better.
Thank you both for the support

**Comment by hopsoft** [comment]
@idoshamun We've improved performance and have noticed a drop in `Client Request Interrupted` notifications. How are things looking on your end?

**Comment by idoshamun** [comment]
@hopsoft thanks for letting me know and working on this. I can still see mainly timeouts in my logs.
This is just an example of what's happening now. I use a circuit breaker to limit my requests in case of a timeout or failure. I am not logging successful requests but you can see the difference between timestamps of timeouts. I think it has improved since the last time I checked, though.
![image](https://user-images.githubusercontent.com/1993245/77400811-730d1700-6db4-11ea-84db-06af0fdc1b5f.png)

**Comment by hopsoft** [comment]
That's great to hear. We still see this on our side too but have worked to reduce the frequency. We currently average `2-5` client requests interrupted every `4,500` requests _(roughly 2k+ ads)_. So this still happens between `0.07%` to `0.15%` of the time right now.  

Server response times on the ad endpoint averaged `79.8` milliseconds over the last 7 days. Of course we have outliers that take longer _i.e. when cached elements rebuild or request queues back up._

**Comment by hopsoft** [comment]
Closing for now. Note that this still happens but we've made good progress. We'll keep an eye on it and continue working to improve response times. Feel free to reopen if needed.
